name: User Story
description: A user story for the backlog
title: "[Story] "
labels: ["story"]
body:
  - type: textarea
    id: story
    attributes:
      label: User Story
      description: "As a [user], I want [action] so that [outcome]"
      placeholder: "As a family member, I want to add a grave to the map so that other relatives can find it"
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: "Binary pass/fail conditions"
      placeholder: |
        - [ ] User can place a pin on the map
        - [ ] User can enter name and dates
        - [ ] Memorial page is created after submit
    validations:
      required: true
  - type: dropdown
    id: size
    attributes:
      label: Size
      options:
        - S (< 1 session)
        - M (1-2 sessions)
        - L (3+ sessions)
    validations:
      required: true
  - type: textarea
    id: out-of-scope
    attributes:
      label: Out of Scope
      description: "What this story explicitly does NOT include"
      placeholder: "Photo upload, inscription text, cemetery autocomplete"
  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      description: "What must be done before this story can start?"
      placeholder: "#12 must be merged first"
