import {
  getCountries,
  getCountryCallingCode,
  type CountryCode,
} from 'libphonenumber-js';

export type { CountryCode } from 'libphonenumber-js';

export interface Country {
  code: CountryCode;
  name: string;
  nameLocal: string;
  dialCode: string;
  flag: string;
}

export const PRIORITY_COUNTRIES: CountryCode[] = [
  'US', 'RU', 'BY', 'UA', 'IL', 'DE', 'KZ', 'UZ',
];

function codeToFlag(code: string): string {
  return code
    .toUpperCase()
    .split('')
    .map((c) => String.fromCodePoint(0x1f1e6 + c.charCodeAt(0) - 65))
    .join('');
}

const COUNTRY_NAMES: Record<string, [en: string, local: string]> = {
  AC: ['Ascension Island', 'Ascension Island'],
  AD: ['Andorra', 'Andorra'],
  AE: ['United Arab Emirates', 'الإمارات'],
  AF: ['Afghanistan', 'افغانستان'],
  AG: ['Antigua & Barbuda', 'Antigua & Barbuda'],
  AI: ['Anguilla', 'Anguilla'],
  AL: ['Albania', 'Shqipëri'],
  AM: ['Armenia', 'Հայաստան'],
  AO: ['Angola', 'Angola'],
  AR: ['Argentina', 'Argentina'],
  AS: ['American Samoa', 'American Samoa'],
  AT: ['Austria', 'Österreich'],
  AU: ['Australia', 'Australia'],
  AW: ['Aruba', 'Aruba'],
  AX: ['Åland Islands', 'Åland'],
  AZ: ['Azerbaijan', 'Azərbaycan'],
  BA: ['Bosnia & Herzegovina', 'Bosna i Hercegovina'],
  BB: ['Barbados', 'Barbados'],
  BD: ['Bangladesh', 'বাংলাদেশ'],
  BE: ['Belgium', 'België'],
  BF: ['Burkina Faso', 'Burkina Faso'],
  BG: ['Bulgaria', 'България'],
  BH: ['Bahrain', 'البحرين'],
  BI: ['Burundi', 'Burundi'],
  BJ: ['Benin', 'Bénin'],
  BL: ['St. Barthélemy', 'Saint-Barthélemy'],
  BM: ['Bermuda', 'Bermuda'],
  BN: ['Brunei', 'Brunei'],
  BO: ['Bolivia', 'Bolivia'],
  BQ: ['Caribbean Netherlands', 'Caribbean Netherlands'],
  BR: ['Brazil', 'Brasil'],
  BS: ['Bahamas', 'Bahamas'],
  BT: ['Bhutan', 'འབྲུག'],
  BW: ['Botswana', 'Botswana'],
  BY: ['Belarus', 'Беларусь'],
  BZ: ['Belize', 'Belize'],
  CA: ['Canada', 'Canada'],
  CC: ['Cocos Islands', 'Cocos Islands'],
  CD: ['Congo - Kinshasa', 'Congo - Kinshasa'],
  CF: ['Central African Republic', 'Centrafrique'],
  CG: ['Congo - Brazzaville', 'Congo - Brazzaville'],
  CH: ['Switzerland', 'Schweiz'],
  CI: ['Côte d\'Ivoire', 'Côte d\'Ivoire'],
  CK: ['Cook Islands', 'Cook Islands'],
  CL: ['Chile', 'Chile'],
  CM: ['Cameroon', 'Cameroun'],
  CN: ['China', '中国'],
  CO: ['Colombia', 'Colombia'],
  CR: ['Costa Rica', 'Costa Rica'],
  CU: ['Cuba', 'Cuba'],
  CV: ['Cape Verde', 'Cabo Verde'],
  CW: ['Curaçao', 'Curaçao'],
  CX: ['Christmas Island', 'Christmas Island'],
  CY: ['Cyprus', 'Κύπρος'],
  CZ: ['Czechia', 'Česko'],
  DE: ['Germany', 'Deutschland'],
  DJ: ['Djibouti', 'Djibouti'],
  DK: ['Denmark', 'Danmark'],
  DM: ['Dominica', 'Dominica'],
  DO: ['Dominican Republic', 'República Dominicana'],
  DZ: ['Algeria', 'الجزائر'],
  EC: ['Ecuador', 'Ecuador'],
  EE: ['Estonia', 'Eesti'],
  EG: ['Egypt', 'مصر'],
  EH: ['Western Sahara', 'الصحراء الغربية'],
  ER: ['Eritrea', 'ኤርትራ'],
  ES: ['Spain', 'España'],
  ET: ['Ethiopia', 'ኢትዮጵያ'],
  FI: ['Finland', 'Suomi'],
  FJ: ['Fiji', 'Fiji'],
  FK: ['Falkland Islands', 'Falkland Islands'],
  FM: ['Micronesia', 'Micronesia'],
  FO: ['Faroe Islands', 'Føroyar'],
  FR: ['France', 'France'],
  GA: ['Gabon', 'Gabon'],
  GB: ['United Kingdom', 'United Kingdom'],
  GD: ['Grenada', 'Grenada'],
  GE: ['Georgia', 'საქართველო'],
  GF: ['French Guiana', 'Guyane française'],
  GG: ['Guernsey', 'Guernsey'],
  GH: ['Ghana', 'Ghana'],
  GI: ['Gibraltar', 'Gibraltar'],
  GL: ['Greenland', 'Kalaallit Nunaat'],
  GM: ['Gambia', 'Gambia'],
  GN: ['Guinea', 'Guinée'],
  GP: ['Guadeloupe', 'Guadeloupe'],
  GQ: ['Equatorial Guinea', 'Guinea Ecuatorial'],
  GR: ['Greece', 'Ελλάδα'],
  GT: ['Guatemala', 'Guatemala'],
  GU: ['Guam', 'Guam'],
  GW: ['Guinea-Bissau', 'Guiné-Bissau'],
  GY: ['Guyana', 'Guyana'],
  HK: ['Hong Kong', '香港'],
  HN: ['Honduras', 'Honduras'],
  HR: ['Croatia', 'Hrvatska'],
  HT: ['Haiti', 'Haïti'],
  HU: ['Hungary', 'Magyarország'],
  ID: ['Indonesia', 'Indonesia'],
  IE: ['Ireland', 'Éire'],
  IL: ['Israel', 'ישראל'],
  IM: ['Isle of Man', 'Isle of Man'],
  IN: ['India', 'भारत'],
  IO: ['British Indian Ocean Territory', 'British Indian Ocean Territory'],
  IQ: ['Iraq', 'العراق'],
  IR: ['Iran', 'ایران'],
  IS: ['Iceland', 'Ísland'],
  IT: ['Italy', 'Italia'],
  JE: ['Jersey', 'Jersey'],
  JM: ['Jamaica', 'Jamaica'],
  JO: ['Jordan', 'الأردن'],
  JP: ['Japan', '日本'],
  KE: ['Kenya', 'Kenya'],
  KG: ['Kyrgyzstan', 'Кыргызстан'],
  KH: ['Cambodia', 'កម្ពុជា'],
  KI: ['Kiribati', 'Kiribati'],
  KM: ['Comoros', 'Comores'],
  KN: ['St. Kitts & Nevis', 'St. Kitts & Nevis'],
  KP: ['North Korea', '조선'],
  KR: ['South Korea', '대한민국'],
  KW: ['Kuwait', 'الكويت'],
  KY: ['Cayman Islands', 'Cayman Islands'],
  KZ: ['Kazakhstan', 'Қазақстан'],
  LA: ['Laos', 'ລາວ'],
  LB: ['Lebanon', 'لبنان'],
  LC: ['St. Lucia', 'St. Lucia'],
  LI: ['Liechtenstein', 'Liechtenstein'],
  LK: ['Sri Lanka', 'ශ්‍රී ලංකා'],
  LR: ['Liberia', 'Liberia'],
  LS: ['Lesotho', 'Lesotho'],
  LT: ['Lithuania', 'Lietuva'],
  LU: ['Luxembourg', 'Lëtzebuerg'],
  LV: ['Latvia', 'Latvija'],
  LY: ['Libya', 'ليبيا'],
  MA: ['Morocco', 'المغرب'],
  MC: ['Monaco', 'Monaco'],
  MD: ['Moldova', 'Moldova'],
  ME: ['Montenegro', 'Crna Gora'],
  MF: ['St. Martin', 'Saint-Martin'],
  MG: ['Madagascar', 'Madagasikara'],
  MH: ['Marshall Islands', 'Marshall Islands'],
  MK: ['North Macedonia', 'Северна Македонија'],
  ML: ['Mali', 'Mali'],
  MM: ['Myanmar', 'မြန်မာ'],
  MN: ['Mongolia', 'Монгол'],
  MO: ['Macao', '澳門'],
  MP: ['Northern Mariana Islands', 'Northern Mariana Islands'],
  MQ: ['Martinique', 'Martinique'],
  MR: ['Mauritania', 'موريتانيا'],
  MS: ['Montserrat', 'Montserrat'],
  MT: ['Malta', 'Malta'],
  MU: ['Mauritius', 'Maurice'],
  MV: ['Maldives', 'ދިވެހިރާއްޖެ'],
  MW: ['Malawi', 'Malawi'],
  MX: ['Mexico', 'México'],
  MY: ['Malaysia', 'Malaysia'],
  MZ: ['Mozambique', 'Moçambique'],
  NA: ['Namibia', 'Namibia'],
  NC: ['New Caledonia', 'Nouvelle-Calédonie'],
  NE: ['Niger', 'Niger'],
  NF: ['Norfolk Island', 'Norfolk Island'],
  NG: ['Nigeria', 'Nigeria'],
  NI: ['Nicaragua', 'Nicaragua'],
  NL: ['Netherlands', 'Nederland'],
  NO: ['Norway', 'Norge'],
  NP: ['Nepal', 'नेपाल'],
  NR: ['Nauru', 'Nauru'],
  NU: ['Niue', 'Niue'],
  NZ: ['New Zealand', 'New Zealand'],
  OM: ['Oman', 'عُمان'],
  PA: ['Panama', 'Panamá'],
  PE: ['Peru', 'Perú'],
  PF: ['French Polynesia', 'Polynésie française'],
  PG: ['Papua New Guinea', 'Papua New Guinea'],
  PH: ['Philippines', 'Pilipinas'],
  PK: ['Pakistan', 'پاکستان'],
  PL: ['Poland', 'Polska'],
  PM: ['St. Pierre & Miquelon', 'Saint-Pierre-et-Miquelon'],
  PR: ['Puerto Rico', 'Puerto Rico'],
  PS: ['Palestine', 'فلسطين'],
  PT: ['Portugal', 'Portugal'],
  PW: ['Palau', 'Palau'],
  PY: ['Paraguay', 'Paraguay'],
  QA: ['Qatar', 'قطر'],
  RE: ['Réunion', 'La Réunion'],
  RO: ['Romania', 'România'],
  RS: ['Serbia', 'Србија'],
  RU: ['Russia', 'Россия'],
  RW: ['Rwanda', 'Rwanda'],
  SA: ['Saudi Arabia', 'السعودية'],
  SB: ['Solomon Islands', 'Solomon Islands'],
  SC: ['Seychelles', 'Seychelles'],
  SD: ['Sudan', 'السودان'],
  SE: ['Sweden', 'Sverige'],
  SG: ['Singapore', 'Singapore'],
  SH: ['St. Helena', 'St. Helena'],
  SI: ['Slovenia', 'Slovenija'],
  SJ: ['Svalbard & Jan Mayen', 'Svalbard & Jan Mayen'],
  SK: ['Slovakia', 'Slovensko'],
  SL: ['Sierra Leone', 'Sierra Leone'],
  SM: ['San Marino', 'San Marino'],
  SN: ['Senegal', 'Sénégal'],
  SO: ['Somalia', 'Soomaaliya'],
  SR: ['Suriname', 'Suriname'],
  SS: ['South Sudan', 'South Sudan'],
  ST: ['São Tomé & Príncipe', 'São Tomé e Príncipe'],
  SV: ['El Salvador', 'El Salvador'],
  SX: ['Sint Maarten', 'Sint Maarten'],
  SY: ['Syria', 'سوريا'],
  SZ: ['Eswatini', 'Eswatini'],
  TA: ['Tristan da Cunha', 'Tristan da Cunha'],
  TC: ['Turks & Caicos', 'Turks & Caicos'],
  TD: ['Chad', 'Tchad'],
  TG: ['Togo', 'Togo'],
  TH: ['Thailand', 'ไทย'],
  TJ: ['Tajikistan', 'Тоҷикистон'],
  TK: ['Tokelau', 'Tokelau'],
  TL: ['Timor-Leste', 'Timor-Leste'],
  TM: ['Turkmenistan', 'Türkmenistan'],
  TN: ['Tunisia', 'تونس'],
  TO: ['Tonga', 'Tonga'],
  TR: ['Turkey', 'Türkiye'],
  TT: ['Trinidad & Tobago', 'Trinidad & Tobago'],
  TV: ['Tuvalu', 'Tuvalu'],
  TW: ['Taiwan', '台灣'],
  TZ: ['Tanzania', 'Tanzania'],
  UA: ['Ukraine', 'Україна'],
  UG: ['Uganda', 'Uganda'],
  US: ['United States', 'United States'],
  UY: ['Uruguay', 'Uruguay'],
  UZ: ['Uzbekistan', 'Oʻzbekiston'],
  VA: ['Vatican City', 'Città del Vaticano'],
  VC: ['St. Vincent & Grenadines', 'St. Vincent & Grenadines'],
  VE: ['Venezuela', 'Venezuela'],
  VG: ['British Virgin Islands', 'British Virgin Islands'],
  VI: ['U.S. Virgin Islands', 'U.S. Virgin Islands'],
  VN: ['Vietnam', 'Việt Nam'],
  VU: ['Vanuatu', 'Vanuatu'],
  WF: ['Wallis & Futuna', 'Wallis-et-Futuna'],
  WS: ['Samoa', 'Samoa'],
  XK: ['Kosovo', 'Kosovë'],
  YE: ['Yemen', 'اليمن'],
  YT: ['Mayotte', 'Mayotte'],
  ZA: ['South Africa', 'South Africa'],
  ZM: ['Zambia', 'Zambia'],
  ZW: ['Zimbabwe', 'Zimbabwe'],
};

function buildCountry(code: CountryCode): Country {
  const [name, nameLocal] = COUNTRY_NAMES[code] ?? [code, code];
  return {
    code,
    name,
    nameLocal,
    dialCode: `+${getCountryCallingCode(code)}`,
    flag: codeToFlag(code),
  };
}

const prioritySet = new Set<CountryCode>(PRIORITY_COUNTRIES);

const priorityList = PRIORITY_COUNTRIES.map(buildCountry);

const restList = getCountries()
  .filter((c): c is CountryCode => !prioritySet.has(c))
  .sort((a, b) => {
    const nameA = COUNTRY_NAMES[a]?.[0] ?? a;
    const nameB = COUNTRY_NAMES[b]?.[0] ?? b;
    return nameA.localeCompare(nameB);
  })
  .map(buildCountry);

export const ALL_COUNTRIES: Country[] = [...priorityList, ...restList];

export const PRIORITY_COUNT = priorityList.length;

const LOCALE_TO_COUNTRY: Record<string, CountryCode> = {
  en: 'US',
  ru: 'RU',
  be: 'BY',
  uk: 'UA',
  he: 'IL',
  de: 'DE',
  kk: 'KZ',
  uz: 'UZ',
};

export const COUNTRIES_BY_CODE: Record<string, Country> = {};
for (const c of ALL_COUNTRIES) {
  COUNTRIES_BY_CODE[c.code] = c;
}

export function getDefaultCountry(locale: string): CountryCode {
  const lang = (locale.split('-')[0] ?? '').toLowerCase();
  return LOCALE_TO_COUNTRY[lang] ?? 'US';
}
